before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: fr8Y2bCMHPPFPFRgLK+u1S0Ee8a41BnZv+6FgeIowaradoCem+J9zquR7QHWtubp7fG+5QlmfKD8/+dbEiKlcT+JRWIkbOgmLxSrqj7rmQqN7amgbFW98v2zESD+lf2AGUeDQZQJkmwRREthEo6UZmuieJje2Ce9K0knDWgmPN2z0RDQOVvj5M3mevTVc/U5/n9un9qmKewpRWoRrqg8cIC/wLMHn3bH8Z4+k3L9gs7CeGU3NtC9bL2DlSWYjYGs1/vpKTSWK5BZXqhikibuJ2EEkZ90iJ5uJjMCO0CRy01+3mNhHdZ/H10NfaMOeK7EjaizJ53Uorafpu8qmzBcozz6JbCijz2J+eEg85xbHsX0OrHaVMvwdZLZoUaC8uKga9neeK2nEdX/a0zFv2QUrziS16DBDOSE/A/ZzP3VftQaC5u2HWReIM2SvAjqe7f1xXgN9ev8qzYtgOYS81shpw6diLL5ySiDEApDx06pm6U7i4VgCv4RDue9+oa0Eb9T+Ubws/GI23Vpxvg1nYG2H1Y615DXm3Eb1dkEDlbVaXx/doEhwJ7lb+BuLbp+acC5AY+ZBqVOmexcu+dKNAJ/WeNy28tYB/ZDm36Wloovzbx0OKI7vILkUGVoKO9NRZKys8yf9uXZ6w7dvCIIgwpQ5/jJTp1UjSxZY6IXvRxIugM= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
